### ISSUE TITLE
Running it has an NPM script

### ISSUE THREAD

**Issue by Berkmann18** [Berkmann18/hashmyjs#1]
# What I did
```cli
npm run hash public/js/faHdl.js
```
Where `hash` was declared in a project's _package.json_ as follows:
```json
  "hash": "hashmyjs"
```

# Actual behaviour
```cli
npm ERR! file /home/maxie/Dropbox/Public/Learning/MEAN/MENP/package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected string in JSON at position 751 while parsing '{
npm ERR!   "name": "menp",
npm ERR!   "description": "Th'
npm ERR! File: /home/maxie/Dropbox/Public/Learning/MEAN/MENP/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maxie/.npm/_logs/2017-12-31T10_55_24_392Z-debug.log
```
Here's the log file:
```cli
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'hash' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose stack Error: Failed to parse json
4 verbose stack Unexpected string in JSON at position 751 while parsing '{
4 verbose stack   "name": "menp",
4 verbose stack   "description": "Th'
4 verbose stack     at parseError (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:11)
4 verbose stack     at parseJson (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:104:26)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:51:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
5 verbose cwd /home/maxie/Dropbox/Public/Learning/MEAN/MENP
6 verbose Linux 4.13.0-rc3-mainline
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "hash"
8 verbose node v9.3.0
9 verbose npm  v5.6.0
10 error file /home/maxie/Dropbox/Public/Learning/MEAN/MENP/package.json
11 error code EJSONPARSE
12 error Failed to parse json
12 error Unexpected string in JSON at position 751 while parsing '{
12 error   "name": "menp",
12 error   "description": "Th'
13 error File: /home/maxie/Dropbox/Public/Learning/MEAN/MENP/package.json
14 error Failed to parse package.json data.
14 error package.json must be actual JSON, not just JavaScript.
14 error
14 error Tell the package author to fix their package.json file. JSON.parse
15 verbose exit [ 1, true ]
```

# Desired behaviour
```cli
- public/js/faHdl.js
sha256-yUDQT9BhhpFLRenWgakaSwWUvEmyqYhawOsEs+o3U18=
```

**Comment by Berkmann18** [comment]
This issue is now resolved, albeit it still requires a work-around to be able to use it as an NPM script.
I will refer the commits in question and test further to see how hacky the absolute path solution is.
