### ISSUE TITLE
Failures when npm start-ing with options

### ISSUE THREAD

**Issue by Berkmann18** [Berkmann18/hashmyjs#13]
`npm start examples/ex0.js` works fine (just like when `-p` is used) but when `-f csv|json` is used it returns this:
```bash
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'csv'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at readFilesSync (/home/maxie/Dropbox/Projects/HashMyJS/src/hashmyjs.js:262:20)
    at Object.run (/home/maxie/Dropbox/Projects/HashMyJS/src/hashmyjs.js:333:46)
    at Command.prgm.arguments.version.description.option.option.option.option.action (/home/maxie/Dropbox/Projects/HashMyJS/index.js:27:9)
    at Command.listener (/home/maxie/Dropbox/Projects/HashMyJS/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/home/maxie/Dropbox/Projects/HashMyJS/node_modules/commander/index.js:653:12)
    at Command.parse (/home/maxie/Dropbox/Projects/HashMyJS/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/maxie/Dropbox/Projects/HashMyJS/index.js:29:4)
```
So it can't differientiate between options arguments and filenames.
It seems to be due to the fact that even tho I specified that `-f, --format` takes an additional argument it remains in the arguments with `-f` cut out.

**Comment by Berkmann18** [comment]
It was raised [here](https://github.com/tj/commander.js/issues/846).

**Comment by Berkmann18** [comment]
So, in fact, the `--` was needed in it when arguments such as `-f` were used such as in: `npm start -- -f csv examples/ex0.js` instead of `npm start -f csv examples/ex0.js`.
And it now works.
To close this issue, the README needs to specify this.

**Comment by Berkmann18** [comment]
Closing since it doesn't seem bothering anymore.
