### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by Berkmann18** [Berkmann18/hashmyjs#22]
The issue was raised [here](https://github.com/facebook/jest/issues/6867) where the error isn't caught on Jest's level.
```bash
writeToFile('some&InvalidFile name.txt', 'test', text)

    expect(function).toThrowError(type)

    Expected the function to throw an error of type:
      "IoError"
    But it didn't throw anything.

      245 | test(`writeToFile('some&InvalidFile name.txt', 'test', text)`, () => {
      246 |   //Target hashmyjs#54
    > 247 |   expect(() => hmj.writeToFile('some&I/nvalidFile name.txt', ['test'])).toThrowError(IoError);
          |                                                                         ^
      248 | });
      249 | 
      250 | /* hash */

      at Object.toThrowError (test/hashmyjs.test.js:247:73)


 RUNS  test/utils.test.js
/home/maxie/Dropbox/Projects/HashMyJS/src/hashmyjs.js:3348
        throw new Error(`Couldn't write in ${filename}` /* err.message, err.context */);
        ^

Error: Couldn't write in some&I/nvalidFile name.txt
    at fs.writeFile.err (/home/maxie/Dropbox/Projects/HashMyJS/src/hashmyjs.js:3348:15)
    at /home/maxie/Dropbox/Projects/HashMyJS/node_modules/graceful-fs/graceful-fs.js:99:16
    at fs.js:1143:7
    at /home/maxie/Dropbox/Projects/HashMyJS/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:145:20)
```

**Comment by Berkmann18** [comment]
@all-contributors Please add @codacy-badger for infra.

**Comment by Berkmann18** [comment]
@all-contributors Please add @codacy-badger for infra
